# Generated by Django 5.0.6 on 2024-07-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_service_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
